repos:
  - repo: local
    hooks:
      # https://github.com/crate-ci/typos/blob/master/.pre-commit-hooks.yaml
      - id: typos
        name: typos
        description: Source code spell checker, binary install
        language: python
        entry: typos
        args: [--write-changes, --force-exclude]
        types: [text]
        stages: [pre-commit, pre-merge-commit, pre-push, manual]
      - id: ruff
        name: ruff
        language: system
        entry: just ruff
        types: [python]
        pass_filenames: false
